# Build and push a docker image 

name: Publish image

on:
  push:
    branches:
      - gw
      - db
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout tyk-build-env
        uses: actions/checkout@v2

      - name: push to github registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: tykio/tyk-build-env
          tag_with_ref: true
